default: &default
  adapter: postgresql
  encoding: utf-8
  host: localhost
  username: postgres
  password: postgres
  pool: 25

development:
  <<: *default
  database: Tweet_develop

test:
  <<: *default
  database: Tweet_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
